CREATE DATABASE IF NOT EXISTS ghost_sheets_db;
USE ghost_sheets_db;

CREATE TABLE IF NOT EXISTS License (
  id VARCHAR(255) PRIMARY KEY,
  `key` VARCHAR(255) UNIQUE NOT NULL,
  status VARCHAR(50) DEFAULT 'ACTIVE',
  maxDevices INT DEFAULT 1,
  expiresAt DATETIME NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  customerName VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Device (
  id VARCHAR(255) PRIMARY KEY,
  licenseId VARCHAR(255) NOT NULL,
  hardwareId VARCHAR(255) NOT NULL,
  deviceName VARCHAR(255),
  lastActive DATETIME DEFAULT CURRENT_TIMESTAMP,
  isRevoked BOOLEAN DEFAULT FALSE,
  FOREIGN KEY (licenseId) REFERENCES License(id) ON DELETE CASCADE,
  UNIQUE (licenseId, hardwareId)
);
